package app.commands;

public enum Commands {
    REGISTER, LOGIN, LOGOUT, ADD_TO_ORDER, CATEGORY, CONFIRM_ORDER, DELETE_FROM_ORDER, MENU, PAY_BILL, SELECT_TABLE,
    SHOW_BILL, ADD_CATEGORY, ADD_DISH, CHANGE_PRICE, DELETE_DISH, FIND_USER;
}
